In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from shapely.geometry import Point
import geopandas as gpd
import copy
import networkx as nx

### Dataset for prediction
Each observation/row is a connection (edge in the network). 
We want the following **route-specific** information: 
* Number of flights ("count") **done**
* Distance (average distance?) **done**
* Tid (average time?)  **done** 


We want the following **airport-specific** information: 
* Degree **done** 
* Clustering coefficient **done**
* Betweenness centrality **done** 
* State? (administrative border?) **excluded**

## Load data 
Data comes from http://stat-computing.org/dataexpo/2009/. 
Flight data relates to the year 2007 (see file StatComp_MER)

In [2]:
# Load data
Flights = pd.read_pickle("Data/Flights18.pkl")
#Airports = pd.read_pickle("Data/Airports.pkl")

# Select variables from which to create network. Must contain two columns of nodes, since 
# nx.from_pandas_edgelist() views each row as an edge. Can also contains attributes, e.g. Distance. 
FlightsNx = Flights[["Origin","Dest","Distance"]]

# Take counts (i.e. how many origin to destination flights in the dataset)
counts = pd.DataFrame(Flights.groupby(["Origin","Dest"])["Year"].count())
counts.columns = ["count"]
FlightsNx = FlightsNx.merge(counts, how = 'left', on = ["Origin","Dest"])

# Drop duplicates 
FlightsNx = FlightsNx.drop_duplicates()

In [3]:
# Create average time for each route
TimeMeans = pd.DataFrame(Flights.groupby(["Origin","Dest"])["ActualElapsedTime"].mean())
# Merge to FlightsNx
FlightsNx = FlightsNx.merge(TimeMeans, how = "left", on = ["Origin", "Dest"])

In [4]:
# Create number of distinct companies on each route 
companies = pd.DataFrame(Flights.groupby(["Origin","Dest"])["UniqueCarrier"].nunique())
companies.columns = ["companies"]
FlightsNx = FlightsNx.merge(companies, how = "left", on = ["Origin", "Dest"])

In [5]:
# Count number of take-offs from origin: 
orig_takeoff = pd.DataFrame(FlightsNx.groupby(["Origin"])["count"].sum())
orig_takeoff.columns = ["origin_takeoff"]
# Merge to network dataset: 
FlightsNx = FlightsNx.merge(orig_takeoff, how = "left", on = "Origin")

# Count number of take-offs from dest
dest_takeoff = pd.DataFrame(FlightsNx.groupby(["Origin"])["count"].sum())
dest_takeoff.columns = ["dest_takeoff"]
FlightsNx = FlightsNx.merge(dest_takeoff, how = "left", left_on = "Dest", right_on = "Origin")

# Count number of landings at destination
dest_lands = pd.DataFrame(FlightsNx.groupby(["Dest"])["count"].sum())
dest_lands.columns = ["dest_landing"]
FlightsNx = FlightsNx.merge(dest_lands, how = "left", on = "Dest")

orig_lands = pd.DataFrame(FlightsNx.groupby(["Dest"])["count"].sum())
orig_lands.columns = ["orig_landing"]
FlightsNx = FlightsNx.merge(orig_lands, how = "left", left_on = "Origin", right_on = "Dest")

# Construct totals (flights)
FlightsNx["Origin_flights"] = FlightsNx["origin_takeoff"]+FlightsNx["orig_landing"]
FlightsNx["Destination_flights"] = FlightsNx["dest_takeoff"]+FlightsNx["dest_landing"]

# Drop auxiliary vars
FlightsNx.drop(["origin_takeoff","dest_takeoff","dest_landing","orig_landing"], axis = 1, inplace = True)

### Degree distribution

In [6]:
Network = nx.from_pandas_edgelist(FlightsNx, source = "Origin", target = "Dest", edge_attr = True)
# docs: https://networkx.github.io/documentation/stable/reference/algorithms/generated/networkx.algorithms.centrality.degree_centrality.html#networkx.algorithms.centrality.degree_centrality 
# Find degree: 
degree_dict = nx.algorithms.centrality.degree_centrality(Network) 
degree_values = list(degree_dict.values())
# Create dataframe
degrees = pd.DataFrame(degree_values)
degrees.columns = ["degree"]
degrees["degree_unnormalized"] = degrees["degree"]*(len(Network.nodes)-1)
degrees["airport"] = degree_dict.keys()

In [7]:
# Add degree to FlightsNx data
FlightsNx = FlightsNx.merge(degrees, how = "left", left_on = "Origin", right_on = "airport")
FlightsNx = FlightsNx.drop("airport", axis = 1)
FlightsNx = FlightsNx.rename(columns = {"degree": "origin_degree", "degree_unnormalized": "origin_degree_unn"})

FlightsNx = FlightsNx.merge(degrees, how = "left", left_on = "Dest", right_on = "airport")
FlightsNx = FlightsNx.drop("airport", axis = 1)
FlightsNx = FlightsNx.rename(columns = {"degree": "dest_degree", "degree_unnormalized": "dest_degree_unn"})

#### Betweenness centrality

In [8]:
btwn_dict = nx.betweenness_centrality(Network)
btwns = pd.DataFrame(list(btwn_dict.values()))
btwns.columns = ["betweenness"]
btwns["airport"] = btwn_dict.keys()

FlightsNx = FlightsNx.merge(btwns, how = "left", left_on = "Origin", right_on = "airport")
FlightsNx = FlightsNx.drop("airport", axis = 1)
FlightsNx = FlightsNx.rename(columns = ({"betweenness":"origin_btwns"}))

FlightsNx = FlightsNx.merge(btwns, how = "left", left_on = "Dest", right_on = "airport")
FlightsNx = FlightsNx.drop("airport", axis = 1)
FlightsNx = FlightsNx.rename(columns = ({"betweenness":"dest_btwns"}))

In [9]:
FlightsNx.drop(["origin_degree","dest_degree"], axis = 1, inplace = True)

In [10]:
FlightsNx = FlightsNx.rename(columns = ({"ActualElapsedTime":"avg_time_mins",
                             "origin_degree_unn":"origin_degree",
                             "dest_degree_unn":"dest_degree"}))

#### Clustering Coefficients

In [11]:
clusters = nx.algorithms.cluster.clustering(Network)
clusters_df = pd.DataFrame(list(clusters.values()))
clusters_df.columns = ["clustering"]
clusters_df["airport"] = clusters.keys()

FlightsNx = FlightsNx.merge(clusters_df, how = "left", left_on = "Origin", right_on = "airport")
FlightsNx = FlightsNx.drop("airport", axis = 1)
FlightsNx = FlightsNx.rename(columns = ({"clustering":"origin_clustcoef"}))

FlightsNx = FlightsNx.merge(clusters_df, how = "left", left_on = "Dest", right_on = "airport")
FlightsNx = FlightsNx.drop("airport", axis = 1)
FlightsNx = FlightsNx.rename(columns = ({"clustering":"dest_clustcoef"}))

In [15]:
FlightsNx.to_pickle("Data/FlightsML18.pkl")
FlightsNx.read_pickle("Data/FlightsML18.pkl")
FlightsNx.tail(2)

,Origin,Dest,Distance,count,avg_time_mins,companies,Origin_flights,Destination_flights,origin_degree,dest_degree,origin_btwns,dest_btwns,origin_clustcoef,dest_clustcoef
0,FLL,IAH,966.0,2164,164.335970,2,195025,347588,82.0,116.0,0.018078,0.036642,0.389341,0.254573
1,SEA,SFO,679.0,9187,129.273400,5,280007,351788,82.0,87.0,0.037868,0.023779,0.400783,0.341353
2,DCA,IAH,1208.0,2735,201.367362,3,265035,347588,90.0,116.0,0.010806,0.036642,0.355056,0.254573
3,LAX,ORD,1744.0,8375,241.003144,5,443002,742622,106.0,176.0,0.031985,0.141564,0.279605,0.138182
4,JAX,EWR,820.0,977,141.293676,3,62682,287738,40.0,95.0,0.001326,0.011473,0.753846,0.338634

In [20]:
FlightsNx[["Origin","origin_degree"]].sort_values("origin_degree", ascending = False).drop_duplicates()

     Origin  origin_degree
1811    ORD          176.0
1622    DFW          170.0
5155    ATL          167.0
3983    DEN          164.0
951     CLT          136.0
6348    MSP          132.0
5345    LAS          117.0
1880    IAH          116.0
5879    DTW          112.0
5835    LAX          106.0
3444    PHX          101.0
248     EWR           95.0
5361    MCO           95.0
3903    SLC           94.0
112     DCA           90.0
269     SFO           87.0
5483    PHL           86.0
6009    FLL           82.0
4985    SEA           82.0
266     IAD           76.0
132     LGA           76.0
5689    SFB           75.0
1358    JFK           72.0
4164    BWI           70.0
4688    TPA           69.0
4412    MDW           68.0
2802    MIA           67.0
6141    SAN           65.0
5694    AUS           65.0
6156    BOS           65.0
...     ...            ...
5982    SPN            1.0
6002    DLG            1.0
2891    ABI            1.0
2892    GCK            1.0
1123    ABY            1.0
5999    AKN            1.0
6317    CYS            1.0
5998    GST            1.0
3913    HIB            1.0
5753    HYA            1.0
5913    VEL            1.0
3888    PIH            1.0
6377    ART            1.0
1065    BQK            1.0
3757    GCC            1.0
2904    ALO            1.0
4034    BFF            1.0
5550    PGV            1.0
3886    LWS            1.0
3889    ABR            1.0
2219    OWB            1.0
3450    YUM            1.0
2868    JLN            1.0
6025    HHH            1.0
3897    BJI            1.0
6254    DRT            1.0
3902    BTM            1.0
3904    CDC            1.0
3736    PAH            1.0
6139    EAR            1.0

[358 rows x 2 columns]

In [13]:
## Homophily? 
## " Does these features contribute? i.e. raise predictive performance?"
## Number of different companies?